version: '3'

services:
  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flask_db
    ports:
      - "3308:3306"  # Expose le port MySQL par défaut 3306

  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    depends_on:
      - mysql-db


